name: Publicar Doc con docfx (Borrando gh-pages)

on:
  push:
    branches:
      - main # O la rama que desees

jobs:
  docfx_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Actualizado a v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # O la versión que estés usando

    - name: Install DocFx globally
      run: dotnet tool update -g docfx --version 2.75.2 # O la versión que uses, o sin versión para la última

    - name: Add .NET tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Generate metadata for DocFx
      run: docfx metadata Bank/docfx.json
      # working-directory: Bank # Si docfx.json está en Bank y prefieres correr desde la raíz del repo

    - name: Build DocFx Site
      run: docfx build Bank/docfx.json
      # working-directory: Bank # El output estará en Bank/_site por defecto

    - name: Publish DocFx site to GitHub Pages (Borrando todo antes)
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Bank/_site               # Directorio que contiene el sitio de DocFx
        publish_branch: gh-pages              # Rama de destino
        force_orphan: true                    # <--- ¡ESTA ES LA CLAVE PARA BORRAR TODO!
        keep_files: false                     # <--- Coherente con force_orphan: true
        allow_empty_commit: false             # Evita commits si no hay cambios en _site
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        # enable_jekyll: false # Generalmente no necesario si DocFx crea .nojekyll
        # disable_nojekyll: false # La acción no tocará el .nojekyll que DocFx pueda generar