name: Bank - Release NuGet Package and Create GitHub Release

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_NAME: Bank.Domain 
  PROJECT_PATH: Bank/Bank.Domain/Bank.Domain.csproj
  TEST_PROJECT_PATH: Bank/Bank.Domain.Tests/Bank.Domain.Tests.csproj
  PACKAGE_OUTPUT_DIRECTORY: out

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  build-test-publish-release:
    name: Build, Test, Publish Bank Package and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      packages: write # Estos permisos son para secrets.GITHUB_TOKEN

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }} && dotnet restore ${{ env.TEST_PROJECT_PATH }}

    - name: Run Unit Tests
      run: dotnet test ${{ env.TEST_PROJECT_PATH }} --no-restore --logger trx

    - name: Build project
      run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

    - name: Get Package Version from .csproj
      id: package_info
      run: |
        VERSION=$(grep -oP '(?<=<Version>).*(?=</Version>)' ${{ env.PROJECT_PATH }} | head -n 1)
        if [ -z "$VERSION" ]; then
          echo "Error: No se pudo extraer la versión del archivo ${{ env.PROJECT_PATH }}"
          exit 1
        fi
        echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
        echo "version_tag=v$VERSION" >> $GITHUB_ENV 
        echo "Versión del paquete leída del .csproj: $VERSION"

    - name: Create NuGet Package
      run: |
        echo "Empaquetando ${{ env.PROJECT_NAME }} con versión: ${{ env.PACKAGE_VERSION }}"
        dotnet pack ${{ env.PROJECT_PATH }} \
          -c Release \
          --no-build \
          -o ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: Setup NuGet Source for GitHub Packages
      run: |
        # Volver a usar el token automático de GitHub
        dotnet nuget add source --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Publish NuGet Package to GitHub Packages
      run: |
        # Volver a usar el token automático de GitHub
        dotnet nuget push "${{ env.PACKAGE_OUTPUT_DIRECTORY }}/${{ env.PROJECT_NAME }}.${{ env.PACKAGE_VERSION }}.nupkg" \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source "github" \
          --skip-duplicate

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.version_tag }} 
        name: "Release ${{ env.version_tag }} (${{ env.PROJECT_NAME }})"
        body: |
          Release del paquete ${{ env.PROJECT_NAME }} versión ${{ env.PACKAGE_VERSION }}.
          Contiene el archivo NuGet generado.
        artifacts: "${{ env.PACKAGE_OUTPUT_DIRECTORY }}/${{ env.PROJECT_NAME }}.${{ env.PACKAGE_VERSION }}.nupkg"
        # Volver a usar el token automático de GitHub
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true